spring:
  application:
    name: luckwine-bgw
  profiles:
    active: dev

# 配置文件加密因子key
jasypt:
  encryptor:
    password: luckwine-bgw

# dubbo最新配置，整合了注册中心配置
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://192.168.85.128:8848
    #    parameters:
    #      namespace: 5f5afe75-b943-40dc-ae5a-6f3e9ab24cf8
    timeout: 6000
    version: 1.0.0
    check: true
    file: ./.dubbo/luckwine_bgw_registry
  scan:
    base-packages: com.luckwine.bgw
  provider:
    version: 1.0.0
    timeout: 6000
    filter: dubboLogFilter,dubboValidationFilter,-validation
    validation: true
    group: dev
  consumer:
    check: false
    version: 1.0.0
    group: dev

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml