spring:
  application:
    name: luckwine-synthesize
  profiles:
    active: dev

# 配置文件加密因子key
jasypt:
  encryptor:
    password: luckwine-synthesize

# dubbo最新配置，整合了注册中心配置
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://192.168.85.128:8848
    timeout: 6000
    version: 1.0.0
    check: true
    file: ./.dubbo/luckwine_synthesize_registry
  scan:
    base-packages: com.luckwine.synthesize
  consumer:
    version: 1.0
    timeout: 6000
    filter: dubboLogFilter,dubboValidationFilter,-validation
    check: false
    group: dev
  provider:
    version: 1.0.0
    timeout: 6000
    #    加载dubbo日志打印过滤器
    filter: dubboLogFilter,dubboValidationFilter,-validation
    group: dev

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml

#springboot管理相关，结合pringboot actuator一起使用
management:
  info:
    git:
      mode: full
    build:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
    #    redis:
    #      enabled: true
    diskspace:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true