#Web服务器本地访问端口
server:
  port: 8006

spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.85.128:3306/luckwine-synthesize?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
     username: root
     password: 123456
     type: com.alibaba.druid.pool.DruidDataSource

dubbo:
  protocol:
    port: -1
  registry:
    address: nacos://192.168.85.128:8848
  provider:
    group: dev
  consumer:
    group: dev

elastic:
  server:
    lists: 192.168.85.128:2181

#玄武短信配置
sms:
  cmHost: ip:port
  wsHost: ip:port
  username: xxx
  password: xxx
  active: false