apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckwine-pgw-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luckwine-pgw
  template:
    metadata:
      labels:
        app: luckwine-pgw
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "www.abc.com"
      containers:
        - name: luckwine-pgw
          image: luckwine-pgw:latest
          imagePullPolicy: IfNotPresent
#          securityContext:
#            readOnlyRootFilesystem: true
#            runAsNonRoot: true
          ports:
            - containerPort: 28038
            - containerPort: 8030
          env:
            - name: JAVA_OPTIONS
              value: -Duser.timezone=GMT+8 -Xms128m -Xmx256m -Dspring.profiles.active=prod -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -Xss1m
          volumeMounts:
            - name: luckwine-volume
              mountPath: /data/applog
      volumes:
        - name: luckwine-volume
          hostPath:
            path: /data/docker/luckwine-pgw