#Web服务器本地访问端口
server:
  port: 8004

#数据源配置 MyBatisConfig.class
spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.85.128:3306/luckwine-marketing?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
     username: root
     password: 123456
     type: com.alibaba.druid.pool.DruidDataSource

elastic:
  server:
    lists: 192.168.85.128:2181

dubbo:
  protocol:
    port: -1
  registry:
    address: nacos://192.168.85.128:8848