# 配置文件加密因子key
jasypt:
  encryptor:
    password: luckwine_acct

#Web服务器本地访问端口
server:
  port: 8008

#数据源配置 MyBatisConfig.class
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luckwine-acct?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml

# dubbo最新配置，整合了注册中心配置
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://192.168.1.14:8848
    parameters:
      namespace: 5f5afe75-b943-40dc-ae5a-6f3e9ab24cf8
    timeout: 6000
    version: 1.0.0
    check: true
    file: ./.dubbo/luckwine_acct_registry
  scan:
    base-packages: com.luckwine.acct
  provider:
    version: 1.0.0
    timeout: 6000
    filter: dubboLogFilter
    validation: true
    group: dev
  consumer:
    check: false
    version: 1.0.0
    group: dev


seata:
  enabled: true
  application-id: luckwine-acct
  tx-service-group: my_test_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  client:
    rm:
      async-commit-buffer-limit: 10000 # 异步提交缓存队列长度（默认10000）
      table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
      report-success-enable: true
      report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
      lock:
        retry-interval:  10 # 校验或占用全局锁重试间隔（默认10ms）
        retry-times:    30 # 校验或占用全局锁重试次数（默认30）
        retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
    tm:
      commit-retry-count:   3 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
      rollback-retry-count: 3 # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    undo:
      data-validation: true # 二阶段回滚镜像校验（默认true开启）
      log-serialization: jackson # undo序列化方式（默认jackson）
      log-table: undo_log  # 自定义undo表名（默认undo_log）
    log:
      exceptionRate: 100 # 日志异常输出概率（默认100）
  service:
    vgroup-mapping:
      my_test_tx_group: default # TC 集群（必须与seata-server保持一致）
    enable-degrade: false # 降级开关
    disable-global-transaction: false # 禁用全局事务（默认false）
    grouplist:
      default: seata-server:8091
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
  registry:
    nacos:
      server-addr: 192.168.1.14:8848
      cluster: default
    type: nacos
  config:
    type: nacos
    nacos:
      server-addr: 192.168.1.14:8848
  enable-auto-data-source-proxy: true

#日志相关
logging:
  config: classpath:logback.xml