spring:
  profiles:
    active: dev
  # 数据源
  datasource:
    url:
    username:
    # ·加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
  jpa:
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none
  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 2
    port: 6379
    timeout: 3000
  #Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      repositories:
        # 仓库中数据存储
        enabled: true
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


# 配置文件加密key
jasypt:
  encryptor:
    password: luckwine-oss-service


# 忽略鉴权url
ignored:
  urls:
  - /oss/permission/getMenuList/**
  - /oss/user/regist
  - /oss/common/**
  - /swagger-ui.html
  - /swagger-resources/**
  - /swagger/**
  - /actuator/**
  - /**/v2/api-docs
  - /**/*.js
  - /**/*.css
  - /**/*.png
  - /**/*.ico
#白名单配置，可以不用登录，访问接口
  - /oss/smslog/**
  - /oss/admodule/**
  - /oss/adcontent/**
  - /oss/acct/**

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.luckwine.oss.module.oss.entity
  typeEnumsPackage: com.luckwine.oss.module.oss.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# Swagger界面内容配置
swagger:
  title: oss system API接口文档
  description: oss Api Documentation
  version: 1.0.1
  termsOfServiceUrl: https://th15817161961.github.io/readme/
  contact:
    name: Howell
    url: https://th15817161961.github.io/readme/
    email: th15817161961@gmail.com


oss:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  endpoint:
  accessKeyId:
  accessKeySecret:
  ossPath: luckwine/oss
  bucketName: luckwine-prod
  ossUrlPath:
  # ES
  elasticsearch:
    nodeClient: 127.0.0.1:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: true

management:
  info:
    git:
      mode: full
    build:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
    redis:
      enabled: true
    diskspace:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

dubbo:
  application:
    name: luckwine-oss-service
    version: 1.0.0
    qos-enable: false
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 6000
    version: 1.0.0
    check: true
    file: ./.dubbo/luckwine_oss_registry
  scan:
    base-packages: com.luckwine.oss
  consumer:
    timeout: 6000
    check: false
    filter: dubboLogFilter,dubboValidationFilter,-validation
    version: 1.0.0
    validation: true