server:
  port: 3333

spring:
  # Redis
  redis:
    host: 192.168.50.131
  #Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 192.168.50.131:9300

portal:
  # ES
  elasticsearch:
    nodeClient: 192.168.50.131:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: true

dubbo:
  registry:
    address: zookeeper://192.168.50.131:2181
