
orderEnv: 1


jasypt:
  encryptor:
    password: luckwine_pgw

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.85.128:3306/luckwine-pgw?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.85.128


dubbo:
  registry:
    address: nacos://192.168.85.128:8848
  provider:
    group: dev
  consumer:
    group: dev

elastic:
  server:
    lists: 192.168.85.128:2181

alipay:
  appId:
  serverUrl:
  ## 应用私钥
  privateKey:
  ## 支付宝的公钥
  publicKey:
  charset: utf-8
  signType: RSA2
  format: json
  returnUrl:
  notifyUrl:
  timeoutExpress : 15m
