spring:
  application:
    name: luckwine-goods
  profiles:
    active: dev
  cache:
    redis:
      time-to-live: 30M
      use-key-prefix: true
      key-prefix: GOODS_CACHE_

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml

logging:
  config: classpath:logback.xml

dubbo:
  scan:
    base-packages: com.luckwine.goods.service
  protocol:
    port: -1
    name: dubbo
  registry:
    check: true
    file: .dubbo/luckwine_goods_registry
    client: curator
  provider:
    validation: true
    filter: dubboLogFilter
    timeout: 6000
    version: 1.0.0
    retries: 0

management:
  endpoint:
    health:
      enabled: true
      show-details: always

