dubbo:
  registry:
    address: 192.168.50.131:2181
spring:
  datasource:
    url: jdbc:mysql://192.168.50.131:3306/luckwine-trade?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: worm010304124

#酒缘网自营店铺
store: 88888888
#流水号：环境标志位
env: 1
#酒缘网收款大账号
recAcct: 1001811040141026993481002